require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.4.2'

target 'SolspaceWallet' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    # :hermes_enabled => false
    :hermes_enabled => true
  )



  target 'SolspaceWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.156.0' })


#   WORKS - NECESSARY FOR LOGROCKET TO WORK MAYBE?
#    post_install do |installer|
#     installer.pods_project.targets.each do |target|
#       if ['logrocket-react-native', 'LogRocket'].include?(target.name)
#         target.build_configurations.each do |config|
#           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#         end
#       end
#     end
#     installer.pods_project.build_configurations.each do |config|
#       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
#     end
#     react_native_post_install(installer)
#   end
# end

def add_flipper_pods!(versions = {})

pod 'react-native-flipper', :path => '../node_modules/react-native-flipper', :configuration => 'Debug'
end

  post_install do |installer|
    # Build Active Architecture Only "NO" (react-native-maps)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
    end

    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
